import "./globals.css";
import { Metadata } from "next";
import styles from "./layout.module.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// RootLayout 컴포넌트는 모든 페이지에 공통으로 적용되는 레이아웃을 정의
// RootLayout 컴포넌트는 children 속성을 통해 자식 컴포넌트를 전달받음
// children 속성은 React.ReactNode 타입으로 정의되어 있음
// React.ReactNode 타입은 React에서 사용하는 모든 타입을 포함하는 타입

// metadata 속성은 페이지의 메타데이터를 정의
// metadata 속성은 next/head 컴포넌트를 통해 페이지의 head 태그에 적용

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <h1>Demo Note</h1>
          <nav className={styles.nav}>
            <Link href="/products">Products</Link>
            <Link href="/contact">Contact</Link>
            <Link href="/about">About</Link>
          </nav>
        </header>
        {children}
        {/* page.tsx가 표시될 자리 (outlet) */}
      </body>
    </html>
  );
}
